// 深渊挂机 · 匿名排行榜 API(Cloudflare Workers + D1)
// 规则(2026-10-02 与用户确认;2026-10-02 战力系统上线,开放 power 榜):
//   - 四个榜:主线榜 zone(最远区域)/ 等级榜 level / 爬塔榜 tower(深渊塔最高层)/
//     战力榜 power(综合战力,客户端折算,不含临时 buff);平局次序键 = 击杀数 → 先到者
//   - 每榜只保留 Top 50,匿名不落榜不留数据(落榜即删)
//   - 不在榜也返回估算名次(COUNT 比我高者 + 1)
//   - 防线:结构校验(数值范围/格式/自洽)+ 语义包络校验(gen-lb-bounds 生成的进度上限)
//     + 昵称过滤 + UUID 小时限流
const BOARDS = ["zone", "level", "tower", "power"];
const TOP_N = 50;
const RATE_PER_HOUR = 12;               // 每 UUID 每小时提交上限
const NAME_MAX = 12;
// power 榜分数为客户端派生量(DPS+EHP+功能加权),服务端无主数据可复核,
// 上限放宽到 1 亿拦离谱值;其余三榜 10 万
const SCORE_MAX = { power: 100_000_000, default: 100_000 };
// 基础敏感词(可按需扩充;命中则改用默认名)
const BAD_WORDS = ["外挂", "代练", "加群", "vx", "wechat", "http", "www", ".com", "fuck", "shit"];

// ---- BEGIN LB-BOUNDS(generated by scripts/gen-lb-bounds.ts —— 勿手改;数值变更后重跑 npm run gen:lb)----
const LB_BOUNDS = {
  generatedAt: "2026-10-08T11:14:11.427Z",
  slack: 4,
  offlineGraceSec: 46800,   // BAL.offline_cap_sec(43200)+1h:playtime 可超墙钟的部分
  initialAgeSec: 2592000,   // 首次提交的 uuid 给 30 天初始墙钟信用(回归玩家/换机导入)
  curve: [
    { t: 600, level: 20, kills: 492, zone: 8, tower: 0, power: 2072 },
    { t: 3600, level: 84, kills: 3944, zone: 124, tower: 0, power: 128272 },
    { t: 14400, level: 224, kills: 18952, zone: 668, tower: 0, power: 1446960 },
  ],
};
// ---- END LB-BOUNDS ----

const CORS = {
  "Access-Control-Allow-Origin": "*",   // 匿名只读榜单 + 无凭据提交,放开来源
  "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, X-Admin-Token",
};
// 管理端 token(/save-sync 的读取与管理写回需要;wrangler secret put ADMIN_TOKEN)
const ADMIN_TOKEN = env => env.ADMIN_TOKEN || "";

export default {
  async fetch(request, env) {
    if (request.method === "OPTIONS") return new Response(null, { headers: CORS });
    const url = new URL(request.url);
    let out, status = 200;
    try {
      if (url.pathname === "/board" && request.method === "GET") {
        const r = await getBoard(env, url.searchParams);
        out = r.body; status = r.status;   // 与 POST 同口径:坏参数 400,不再 200+error
      } else if (url.pathname === "/submit" && request.method === "POST") {
        const r = await submit(env, await request.json());
        out = r.body; status = r.status;
      } else if (url.pathname === "/save-sync" && request.method === "GET") {
        const token = request.headers.get("x-admin-token") ?? url.searchParams.get("token") ?? "";
        const r = await saveSyncGet(env, url.searchParams, token);
        out = r.body; status = r.status;
      } else if (url.pathname === "/save-sync" && request.method === "POST") {
        const token = request.headers.get("x-admin-token") ?? "";
        const r = await saveSyncPost(env, await request.json(), token);
        out = r.body; status = r.status;
      } else {
        out = { error: "not found" }; status = 404;
      }
    } catch (e) {
      out = { error: String((e && e.message) || e) }; status = 400;
    }
    return new Response(JSON.stringify(out),
      { status, headers: { ...CORS, "Content-Type": "application/json; charset=utf-8" } });
  },
};

// ---------------------------------------------------------------- 校验
function intOrNull(v, lo, hi) {
  const n = Number(v);
  if (!Number.isFinite(n)) return null;
  const i = Math.trunc(n);
  return (i >= lo && i <= hi) ? i : null;   // 越界视为非法,丢弃提交
}
const UUID_RE = /^[a-zA-Z0-9_-]{8,40}$/;

function cleanName(raw) {
  let s = String(raw ?? "").replace(/[\u0000-\u001f\u007f]/g, "").trim();
  const low = s.toLowerCase();
  for (const w of BAD_WORDS) if (low.includes(w)) return "";
  if (s.length > NAME_MAX) s = s.slice(0, NAME_MAX);
  return s;
}

async function checkRate(env, uuid, scope = "") {
  const bucket = Math.floor(Date.now() / 3600_000);   // 小时桶
  const key = scope ? `${uuid}:${scope}:${bucket}` : `${uuid}:${bucket}`;
  const r = await env.DB.prepare(
    "INSERT INTO rate (key, bucket, n) VALUES (?, ?, 1) " +
    "ON CONFLICT(key) DO UPDATE SET n = n + 1 RETURNING n"
  ).bind(key, bucket).first();
  if (r && r.n === 1)   // 本 UUID 本小时首次提交:顺带清理过期桶
    await env.DB.prepare("DELETE FROM rate WHERE bucket < ?").bind(bucket - 2).run();
  return !r || r.n <= RATE_PER_HOUR;
}

// ---------------------------------------------------------------- 语义包络(与 server.cjs 同)
// LB_BOUNDS 由 scripts/gen-lb-bounds.ts 以默认数值跑参考自动脚本生成(npm run gen:lb):
// 指标 ≤ 包络(playtime);塔层 ≤ 击杀;playtime ≤ uuid 首见墙钟 + 离线宽限,增量再卡墙钟。
function curveAt(metric, t) {
  const pts = LB_BOUNDS.curve;
  if (t <= pts[0].t) return pts[0][metric];
  for (let i = 1; i < pts.length; i++) {
    if (t <= pts[i].t) {
      const a = pts[i - 1], b = pts[i];
      return a[metric] + (b[metric] - a[metric]) * (t - a.t) / (b.t - a.t);
    }
  }
  const a = pts[pts.length - 2], b = pts[pts.length - 1];   // 末段斜率外推:对凹曲线偏宽,仍是合法上界
  return b[metric] + (b[metric] - a[metric]) * (t - b.t) / (b.t - a.t);
}

/** 返回不合格字段名(null = 通过)。v = 已过结构校验的字段;prev = 该榜已有行(可 null) */
function implausible(v, firstSeenTs, prev) {
  const now = Date.now();
  if (v.level > curveAt("level", v.playtime)) return "level";
  if (v.kills > curveAt("kills", v.playtime)) return "kills";
  if (v.max_zone > curveAt("zone", v.playtime)) return "zone";
  if (v.max_tower > v.kills) return "tower";   // 每层至少一杀(击杀计数单点 combat.ts)
  if (v.board === "power" && v.score > curveAt("power", v.playtime)) return "power";
  const ageSec = firstSeenTs != null ? (now - firstSeenTs) / 1000 : LB_BOUNDS.initialAgeSec;
  if (v.playtime > ageSec + LB_BOUNDS.offlineGraceSec) return "playtime";
  if (prev && prev.playtime != null) {
    const gapSec = Math.max(0, (now - (prev.updated_at ?? now)) / 1000);
    if (v.playtime > prev.playtime + gapSec + LB_BOUNDS.offlineGraceSec) return "playtime-delta";
  }
  return null;
}

/** uuid 首见时刻(不存在则记为现在);RETURNING 单语句读写 */
async function firstSeenOf(env, uuid) {
  const r = await env.DB.prepare(
    "INSERT INTO first_seen (uuid, ts) VALUES (?, ?) " +
    "ON CONFLICT(uuid) DO UPDATE SET ts = ts RETURNING ts"
  ).bind(uuid, Date.now()).first();
  return r ? r.ts : Date.now();
}

// ---------------------------------------------------------------- 存档周期上云(/save-sync)
// 玩家端上行:POST {uuid,name,save}(无 token;独立小时限流 + 同套语义包络);
// 管理端:GET ?token=[&uuid=] 列表/单取,POST 带 X-Admin-Token 头 = 管理写回
// (跳过包络与限流,便于造测试档)。token 未配置时管理端点 503。
async function syncRow(env, uuid) {
  return env.DB.prepare(
    "SELECT playtime, updated_at FROM save_sync WHERE uuid = ?"
  ).bind(uuid).first() || null;
}

async function saveSyncPost(env, body, token) {
  const uuid = String(body.uuid ?? "");
  if (!UUID_RE.test(uuid)) return { body: { error: "bad uuid" }, status: 400 };
  const save = body.save;
  if (save === null || typeof save !== "object" || Array.isArray(save))
    return { body: { error: "bad save" }, status: 400 };
  const text = JSON.stringify(save);
  if (text.length > 60_000) return { body: { error: "save too large" }, status: 400 };

  const num = (v, dflt) => (typeof v === "number" && Number.isFinite(v))
    ? Math.max(0, Math.trunc(v)) : dflt;
  const v = {
    board: "sync", score: 0,
    kills: num(save.stats?.kills, 0), playtime: num(save.playtime, 0),
    level: Math.max(1, num(save.level, 1)), max_zone: Math.max(1, num(save.stats?.max_zone, 1)),
    max_tower: num(save.tower?.max_floor, 0),
  };
  const isAdmin = ADMIN_TOKEN(env) !== "" && token !== "" && token === ADMIN_TOKEN(env);
  if (!isAdmin) {
    const bad = implausible(v, await firstSeenOf(env, uuid), await syncRow(env, uuid));
    if (bad) return { body: { error: `implausible ${bad}` }, status: 400 };
    if (!(await checkRate(env, uuid, "sync"))) return { body: { error: "rate limited" }, status: 429 };
  }

  const name = cleanName(body.name);   // 空 = 保留库中旧名(INSERT 时给默认名)
  const now = Date.now();
  await env.DB.prepare(
    "INSERT INTO save_sync (uuid, name, save_json, playtime, level, kills, max_zone, max_tower, bytes, updated_at) " +
    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) " +
    "ON CONFLICT(uuid) DO UPDATE SET " +
    "name = CASE WHEN excluded.name = '' THEN save_sync.name ELSE excluded.name END, " +
    "save_json = excluded.save_json, playtime = excluded.playtime, level = excluded.level, " +
    "kills = excluded.kills, max_zone = excluded.max_zone, max_tower = excluded.max_tower, " +
    "bytes = excluded.bytes, updated_at = excluded.updated_at"
  ).bind(uuid, name, text, v.playtime, v.level, v.kills, v.max_zone, v.max_tower, text.length, now).run();
  return { body: { ok: true, updated_at: now, bytes: text.length }, status: 200 };
}

async function saveSyncGet(env, params, token) {
  if (ADMIN_TOKEN(env) === "") return { body: { error: "admin token not configured" }, status: 503 };
  if (token !== ADMIN_TOKEN(env)) return { body: { error: "bad token" }, status: 403 };
  const uuid = params.get("uuid") ?? "";
  if (uuid) {
    const r = await env.DB.prepare(
      "SELECT save_json, updated_at FROM save_sync WHERE uuid = ?"
    ).bind(uuid).first();
    if (!r) return { body: { error: "not found" }, status: 404 };
    return { body: { uuid, save: JSON.parse(r.save_json), updated_at: r.updated_at }, status: 200 };
  }
  const rows = await env.DB.prepare(
    "SELECT uuid, name, level, playtime, kills, max_zone, max_tower, bytes, updated_at " +
    "FROM save_sync ORDER BY updated_at DESC LIMIT 200"
  ).all();
  return { body: { count: (rows.results ?? []).length, saves: rows.results ?? [] }, status: 200 };
}

// ---------------------------------------------------------------- 周榜(2.3)
/** 当前 ISO 周标识(周一为一周之始),与客户端 game.ts isoWeekKey 同口径 */
function weekKeyNow() {
  const t = new Date();
  const d = new Date(t.getFullYear(), t.getMonth(), t.getDate());
  d.setDate(d.getDate() + 4 - (d.getDay() || 7));       // 本周四(ISO 定年口径)
  const year = d.getFullYear();
  const jan1 = new Date(year, 0, 1);
  const week = Math.ceil(((d.getTime() - jan1.getTime()) / 86400000 + 1) / 7);
  return `${year}-W${week}`;
}

// ---------------------------------------------------------------- 读榜
async function getBoard(env, params) {
  const board = params.get("b") ?? "";
  if (!BOARDS.includes(board)) return { body: { error: "bad board" }, status: 400 };
  const uuid = params.get("uuid") ?? "";
  const weekly = params.get("period") === "week";
  const week = weekly ? weekKeyNow() : null;
  const table = weekly ? "entries_weekly" : "entries";
  const weekFilter = weekly ? " AND week = ?" : "";
  const bindBase = weekly ? [board, week] : [board];
  const top = await env.DB.prepare(
    "SELECT uuid, name, score, kills, playtime, level, max_zone, updated_at " +
    `FROM ${table} WHERE board = ?${weekFilter} ` +
    "ORDER BY score DESC, kills DESC, updated_at ASC LIMIT ?"
  ).bind(...bindBase, TOP_N).all();
  if (weekly) {
    // 懒清理:旧周数据即刻清(每 uuid 每周至多一行,常态量级极小)
    await env.DB.prepare("DELETE FROM entries_weekly WHERE week < ?").bind(week).run();
  }
  const rows = (top.results ?? []).map(r => {
    const { uuid: rowUuid, ...rest } = r;
    return { ...rest, is_me: rowUuid === uuid };   // 只回传 is_me,不外泄他人 uuid
  });
  let you = null;
  if (UUID_RE.test(uuid)) {
    const mine = await fullRow(env, board, uuid, table, week);
    if (mine) {
      you = { rank: await rankOf(env, board, mine.score, mine.kills, table, week),
              inTop: true, score: mine.score, kills: mine.kills };
    }
  }
  return { body: { board, period: weekly ? "week" : "all", top: rows, you }, status: 200 };
}

// ---------------------------------------------------------------- 提交
async function submit(env, body) {
  const board = String(body.board ?? "");
  if (!BOARDS.includes(board)) return { body: { error: "bad board" }, status: 400 };
  const uuid = String(body.uuid ?? "");
  if (!UUID_RE.test(uuid)) return { body: { error: "bad uuid" }, status: 400 };

  // 结构校验:宽范围硬上限,拦"物理不可能"的离谱值(第一版;seed 重放复核为后续项)
  const score = intOrNull(body.score, 1, board === "power" ? SCORE_MAX.power : SCORE_MAX.default);
  const kills = intOrNull(body.kills, 0, 1_000_000_000);
  const playtime = intOrNull(body.playtime, 0, 3.2e10);        // ≤1000 年
  const level = intOrNull(body.level, 1, 5_000);
  const max_zone = intOrNull(body.max_zone, 1, 10_000);
  const max_tower = intOrNull(body.max_tower ?? 0, 0, 100_000);
  if ([score, kills, playtime, level, max_zone, max_tower].some(v => v === null))
    return { body: { error: "bad values" }, status: 400 };
  // 自洽:score 与对应主数据一致(tower 榜要求 max_tower ≥ 1,即已通至少一层);
  // power 榜为客户端派生量,无主数据可对,仅靠上限+限流防线
  if ((board === "zone" && score !== max_zone) ||
      (board === "level" && score !== level) ||
      (board === "tower" && score !== max_tower))
    return { body: { error: "score mismatch" }, status: 400 };

  // 语义包络:拦"结构合法但物理不可能"的进度;先于限流(被拒不烧限流额度)
  const mine = await fullRow(env, board, uuid);
  const bad = implausible(
    { board, score, kills, playtime, level, max_zone, max_tower },
    await firstSeenOf(env, uuid), mine);
  if (bad) return { body: { error: `implausible ${bad}` }, status: 400 };

  if (!(await checkRate(env, uuid)))
    return { body: { error: "rate limited" }, status: 429 };

  const name = cleanName(body.name) || `深渊行者#${uuid.slice(0, 4).toUpperCase()}`;
  const now = Date.now();

  // 榜内已有自己且新分更低:不覆盖(只升不降,防误提交掉分)
  if (mine && score < mine.score) {
    return { body: { rank: await rankOf(env, board, mine.score, mine.kills),
                     inTop: true, updated: false }, status: 200 };
  }

  // 是否够格进 Top50
  const cnt = await env.DB.prepare(
    "SELECT COUNT(*) AS n FROM entries WHERE board = ?").bind(board).first();
  let qualified = (cnt?.n ?? 0) < TOP_N;
  if (!qualified) {
    const lowest = await env.DB.prepare(
      "SELECT score, kills FROM entries WHERE board = ? " +
      "ORDER BY score DESC, kills DESC, updated_at ASC LIMIT 1 OFFSET ?"
    ).bind(board, TOP_N - 1).first();
    qualified = score > lowest.score ||
                (score === lowest.score && kills > lowest.kills);
  }

  if (qualified) {
    await env.DB.prepare(
      "INSERT INTO entries (board, uuid, name, score, kills, playtime, level, max_zone, max_tower, updated_at) " +
      "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) " +
      "ON CONFLICT(board, uuid) DO UPDATE SET " +
      "name = excluded.name, score = excluded.score, kills = excluded.kills, " +
      "playtime = excluded.playtime, level = excluded.level, " +
      "max_zone = excluded.max_zone, max_tower = excluded.max_tower, updated_at = excluded.updated_at"
    ).bind(board, uuid, name, score, kills, playtime, level, max_zone, max_tower, now).run();
    // 裁剪:只留 Top50(落榜即删——匿名不留数据)
    await env.DB.prepare(
      "DELETE FROM entries WHERE board = ? AND rowid NOT IN (" +
      "  SELECT rowid FROM entries WHERE board = ? " +
      "  ORDER BY score DESC, kills DESC, updated_at ASC LIMIT ?)"
    ).bind(board, board, TOP_N).run();
  }

  // —— 周榜(2.3):独立于终身榜记录本周成绩(不进终身 Top50 也有本周席位);
  //    同周只升不降,跨周覆盖;每 uuid 每榜每周至多一行
  {
    const week = weekKeyNow();
    const wmine = await fullRow(env, board, uuid, "entries_weekly", week);
    if (!(wmine && score < wmine.score)) {
      await env.DB.prepare(
        "INSERT INTO entries_weekly (board, uuid, week, name, score, kills, playtime, level, max_zone, max_tower, updated_at) " +
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) " +
        "ON CONFLICT(board, uuid) DO UPDATE SET " +
        "week = excluded.week, name = excluded.name, score = excluded.score, kills = excluded.kills, " +
        "playtime = excluded.playtime, level = excluded.level, " +
        "max_zone = excluded.max_zone, max_tower = excluded.max_tower, updated_at = excluded.updated_at"
      ).bind(board, uuid, week, name, score, kills, playtime, level, max_zone, max_tower, now).run();
      await env.DB.prepare(
        "DELETE FROM entries_weekly WHERE board = ? AND week = ? AND rowid NOT IN (" +
        "  SELECT rowid FROM entries_weekly WHERE board = ? AND week = ? " +
        "  ORDER BY score DESC, kills DESC, updated_at ASC LIMIT ?)"
      ).bind(board, week, board, week, TOP_N).run();
    }
  }

  const rank = await rankOf(env, board, score, kills);
  return { body: { rank, inTop: qualified && rank <= TOP_N, updated: qualified }, status: 200 };
}

async function fullRow(env, board, uuid, table = "entries", week = null) {
  const weekFilter = week ? " AND week = ?" : "";
  const sql = `SELECT score, kills, playtime, updated_at FROM ${table} WHERE board = ? AND uuid = ?${weekFilter}`;
  return week
    ? env.DB.prepare(sql).bind(board, uuid, week).first()
    : env.DB.prepare(sql).bind(board, uuid).first();
}
async function rankOf(env, board, score, kills, table = "entries", week = null) {
  const weekFilter = week ? " AND week = ?" : "";
  const higher = await env.DB.prepare(
    `SELECT COUNT(*) AS n FROM ${table} WHERE board = ?${weekFilter} ` +
    "AND (score > ? OR (score = ? AND kills > ?))"
  ).bind(...(week ? [board, week] : [board]), score, score, kills).first();
  return (higher?.n ?? 0) + 1;
}
