name = "abyss-leaderboard"
main = "worker.js"
compatibility_date = "2024-09-01"

[[d1_databases]]
binding = "DB"
database_name = "abyss-leaderboard"
# database_id:由 `wrangler d1 create abyss-leaderboard` 输出(2026-10-02 上线时创建)
database_id = "0cc22b11-d0c7-4cf6-813d-de40c79a4456"
