/** 排行榜语义包络生成器 —— 以默认数值跑参考自动脚本,生成各时长的合法进度上限,
 * 注入两端服务的托管块(server/leaderboard-ecs/server.cjs 与 workers/leaderboard/worker.js)。
 *
 * 用法: npm run gen:lb     (改动 src/core 数值后重跑,然后重新部署两端)
 *
 * 原理:
 *   - 用与 parity 对拍同款的核心(src/core,不加载任何覆盖)跑 autopilot 参考脚本,
 *     时长锚点 10min / 1h / 4h × 三职业,记录 level / kills / max_zone / max_tower / power;
 *   - 各指标取职业最大值 × SLACK 作为「该游戏时长内的包络上限」(服务端按 playtime
 *     分段线性插值,超出末锚点按末段斜率外推——对凹曲线偏宽,仍是合法上界);
 *   - max_tower 另受 max_tower ≤ kills 约束(每层至少一杀;击杀计数单点 combat.ts);
 *   - 包络随数值变化重新生成,两端文件中的托管块保持逐字节一致(冒烟测试守卫)。
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { Game } from "../src/core/game.ts";
import { View } from "../src/core/view.ts";
import { autopilot } from "../src/core/host.ts";
import { heroPower } from "../src/core/power.ts";
import { BAL } from "../src/core/data.ts";

const TICK = 0.1;                            // 与 sim.ts 同步长
const SEED = 20260930;                       // 与 parity 默认种子同
const DURATIONS = [600, 3600, 14400];        // 锚点:10min / 1h / 4h(游戏时长)
const CLASSES = ["warrior", "mage", "ranger"];
const SLACK = 4;                             // 包络放宽倍数(真玩家优于参考脚本的安全余量)
const ROOT = process.cwd();                  // 从仓库根运行(npm run gen:lb)

interface Sample { level: number; kills: number; zone: number; tower: number; power: number }

/** 与 sim.ts runSim 同构的参考局(autopilot 全自动),返回终局指标 */
function runRef(sec: number, cls: string): Sample {
  const g = new Game(SEED);
  g.view = new View();
  g.chooseClass(cls);
  const steps = Math.trunc(sec / TICK);
  for (let i = 0; i < steps; i++) {
    g.tick(TICK);
    g.events.length = 0;
    autopilot(g, true);
  }
  return {
    level: g.level,
    kills: g.stats.kills,
    zone: g.stats.max_zone,
    tower: g.tower.max_floor,
    power: Math.round(heroPower(g, false).total),
  };
}

console.log(`== 参考局:${DURATIONS.join("/")} 秒 × ${CLASSES.join("/")} × seed ${SEED}(全默认数值)`);
const curve = DURATIONS.map(t => {
  const best: Sample = { level: 0, kills: 0, zone: 0, tower: 0, power: 0 };
  for (const cls of CLASSES) {
    const s = runRef(t, cls);
    for (const k of Object.keys(best) as (keyof Sample)[])
      best[k] = Math.max(best[k], s[k]);
    console.log(`   t=${t}s ${cls.padEnd(7)} Lv${s.level} kills=${s.kills} zone=${s.zone} tower=${s.tower} power=${s.power}`);
  }
  return {
    t,
    level: Math.round(best.level * SLACK),
    kills: Math.round(best.kills * SLACK),
    zone: Math.round(best.zone * SLACK),
    tower: Math.round(best.tower * SLACK),
    power: Math.round(best.power * SLACK),
  };
});

const offlineGraceSec = BAL.offline_cap_sec + 3600;   // 离线收益上限 + 1h 余量
const block = `// ---- BEGIN LB-BOUNDS(generated by scripts/gen-lb-bounds.ts —— 勿手改;数值变更后重跑 npm run gen:lb)----
const LB_BOUNDS = {
  generatedAt: "${new Date().toISOString()}",
  slack: ${SLACK},
  offlineGraceSec: ${offlineGraceSec},   // BAL.offline_cap_sec(${BAL.offline_cap_sec})+1h:playtime 可超墙钟的部分
  initialAgeSec: ${30 * 86400},   // 首次提交的 uuid 给 30 天初始墙钟信用(回归玩家/换机导入)
  curve: [
${curve.map(c => `    { t: ${c.t}, level: ${c.level}, kills: ${c.kills}, zone: ${c.zone}, tower: ${c.tower}, power: ${c.power} },`).join("\n")}
  ],
};
// ---- END LB-BOUNDS ----`;

const TARGETS = [
  join(ROOT, "server/leaderboard-ecs/server.cjs"),
  join(ROOT, "workers/leaderboard/worker.js"),
];
const BEGIN = "// ---- BEGIN LB-BOUNDS";
const END = "// ---- END LB-BOUNDS ----";

for (const path of TARGETS) {
  const src = readFileSync(path, "utf8");
  const b0 = src.indexOf(BEGIN);
  let out: string;
  if (b0 >= 0) {
    const e0 = src.indexOf(END, b0);
    if (e0 < 0) throw new Error(`${path}: 有 BEGIN 无 END,托管块损坏,请人工检查`);
    out = src.slice(0, b0) + block + src.slice(e0 + END.length);
  } else {
    const anchor = src.indexOf("const BAD_WORDS = ");
    if (anchor < 0) throw new Error(`${path}: 找不到 BAD_WORDS 锚点`);
    const lineEnd = src.indexOf("\n", anchor);
    out = src.slice(0, lineEnd + 1) + "\n" + block + "\n" + src.slice(lineEnd + 1);
  }
  writeFileSync(path, out);
  console.log(`== 已注入 ${path}`);
}
console.log(`== 完成:包络(×${SLACK})锚点 ${DURATIONS.join("/")}s;记得重新部署两端`);
