// 深渊挂机 · 匿名排行榜 API —— 阿里云 ECS 版(零依赖,Node ≥ 23.4 自带 node:sqlite)
// 与 workers/leaderboard/worker.js 逻辑逐行同构:四榜/Top50/小时限流/只升不降/
// 估算名次/昵称过滤/结构校验/语义包络校验/存档周期上云(/save-sync,管理端需 ADMIN_TOKEN);
// 数据存同目录 leaderboard.db(备份 = 复制该文件)。
//
// 部署(阿里云 ECS):
//   1. 安全组放行自定义 TCP 端口 8787(入方向,源 0.0.0.0/0)
//   2. 安装 Node ≥ 23.4(22 需 --experimental-sqlite);scp 本文件上服务器
//   3. 启动: PORT=8787 node server.js   (常驻用 systemd 或 nohup,见 README)
//   4. 客户端构建: VITE_LB_API=http://<公网IP>:8787 npx vite build
//      (注意:HTTPS 页面(如 github.io)不能拉 http 接口——Web 版继续用 workers.dev,
//       本端点给 APK/TapTap 构建(native WebView 无混合内容限制)或后续配域名+证书用)
//
// 健康检查: GET /healthz → {ok:true, boards:4}

"use strict";
const http = require("node:http");
const { DatabaseSync } = require("node:sqlite");

const PORT = Number(process.env.PORT || 8787);
const DB_PATH = process.env.DB_PATH || __dirname + "/leaderboard.db";

// ---------------------------------------------------------------- 规则(与 worker.js 同)
const BOARDS = ["zone", "level", "tower", "power"];
const TOP_N = 50;
const RATE_PER_HOUR = 12;
const NAME_MAX = 12;
const SCORE_MAX = { power: 100_000_000, default: 100_000 };
const BAD_WORDS = ["外挂", "代练", "加群", "vx", "wechat", "http", "www", ".com", "fuck", "shit"];

// ---- BEGIN LB-BOUNDS(generated by scripts/gen-lb-bounds.ts —— 勿手改;数值变更后重跑 npm run gen:lb)----
const LB_BOUNDS = {
  generatedAt: "2026-10-08T12:00:52.142Z",
  slack: 4,
  offlineGraceSec: 46800,   // BAL.offline_cap_sec(43200)+1h:playtime 可超墙钟的部分
  initialAgeSec: 2592000,   // 首次提交的 uuid 给 30 天初始墙钟信用(回归玩家/换机导入)
  curve: [
    { t: 600, level: 20, kills: 492, zone: 8, tower: 0, power: 2072 },
    { t: 3600, level: 84, kills: 3944, zone: 124, tower: 0, power: 128272 },
    { t: 14400, level: 224, kills: 18952, zone: 668, tower: 0, power: 1446960 },
  ],
};
// ---- END LB-BOUNDS ----

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, X-Admin-Token",
};

// 管理端 token(/save-sync 的读取与管理写回需要;部署时设环境变量 ADMIN_TOKEN)
const ADMIN_TOKEN = process.env.ADMIN_TOKEN || "";

// ---------------------------------------------------------------- 数据库
const db = new DatabaseSync(DB_PATH);
db.exec(`
CREATE TABLE IF NOT EXISTS entries (
  board TEXT NOT NULL, uuid TEXT NOT NULL,
  name TEXT NOT NULL, score INTEGER NOT NULL,
  kills INTEGER NOT NULL DEFAULT 0, playtime INTEGER NOT NULL DEFAULT 0,
  level INTEGER NOT NULL DEFAULT 1, max_zone INTEGER NOT NULL DEFAULT 1,
  max_tower INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL,
  PRIMARY KEY (board, uuid)
);
CREATE INDEX IF NOT EXISTS idx_entries_rank ON entries(board, score DESC, kills DESC);
CREATE TABLE IF NOT EXISTS entries_weekly (
  board TEXT NOT NULL, uuid TEXT NOT NULL, week TEXT NOT NULL,
  name TEXT NOT NULL, score INTEGER NOT NULL,
  kills INTEGER NOT NULL DEFAULT 0, playtime INTEGER NOT NULL DEFAULT 0,
  level INTEGER NOT NULL DEFAULT 1, max_zone INTEGER NOT NULL DEFAULT 1,
  max_tower INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL,
  PRIMARY KEY (board, uuid)
);
CREATE INDEX IF NOT EXISTS idx_weekly_rank ON entries_weekly(week, board, score DESC, kills DESC);
CREATE TABLE IF NOT EXISTS rate (
  key TEXT PRIMARY KEY, bucket INTEGER NOT NULL, n INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS first_seen (
  uuid TEXT PRIMARY KEY, ts INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS save_sync (
  uuid TEXT PRIMARY KEY, name TEXT NOT NULL,
  save_json TEXT NOT NULL, playtime INTEGER NOT NULL DEFAULT 0,
  level INTEGER NOT NULL DEFAULT 1, kills INTEGER NOT NULL DEFAULT 0,
  max_zone INTEGER NOT NULL DEFAULT 1, max_tower INTEGER NOT NULL DEFAULT 0,
  bytes INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL
);
`);

// ---------------------------------------------------------------- 校验(与 worker.js 同)
function intOrNull(v, lo, hi) {
  const n = Number(v);
  if (!Number.isFinite(n)) return null;
  const i = Math.trunc(n);
  return (i >= lo && i <= hi) ? i : null;
}
const UUID_RE = /^[a-zA-Z0-9_-]{8,40}$/;

function cleanName(raw) {
  let s = String(raw ?? "").replace(/[\u0000-\u001f\u007f]/g, "").trim();
  const low = s.toLowerCase();
  for (const w of BAD_WORDS) if (low.includes(w)) return "";
  if (s.length > NAME_MAX) s = s.slice(0, NAME_MAX);
  return s;
}

function checkRate(uuid, scope = "") {
  const bucket = Math.floor(Date.now() / 3600_000);
  const key = scope ? `${uuid}:${scope}:${bucket}` : `${uuid}:${bucket}`;
  const r = db.prepare(
    "INSERT INTO rate (key, bucket, n) VALUES (?, ?, 1) " +
    "ON CONFLICT(key) DO UPDATE SET n = n + 1 RETURNING n"
  ).get(key, bucket);
  if (r && r.n === 1)
    db.prepare("DELETE FROM rate WHERE bucket < ?").run(bucket - 2);
  return !r || r.n <= RATE_PER_HOUR;
}

// ---------------------------------------------------------------- 语义包络(与 worker.js 同)
// LB_BOUNDS 由 scripts/gen-lb-bounds.ts 以默认数值跑参考自动脚本生成(npm run gen:lb):
// 指标 ≤ 包络(playtime);塔层 ≤ 击杀;playtime ≤ uuid 首见墙钟 + 离线宽限,增量再卡墙钟。
function curveAt(metric, t) {
  const pts = LB_BOUNDS.curve;
  if (t <= pts[0].t) return pts[0][metric];
  for (let i = 1; i < pts.length; i++) {
    if (t <= pts[i].t) {
      const a = pts[i - 1], b = pts[i];
      return a[metric] + (b[metric] - a[metric]) * (t - a.t) / (b.t - a.t);
    }
  }
  const a = pts[pts.length - 2], b = pts[pts.length - 1];   // 末段斜率外推:对凹曲线偏宽,仍是合法上界
  return b[metric] + (b[metric] - a[metric]) * (t - b.t) / (b.t - a.t);
}

/** 返回不合格字段名(null = 通过)。v = 已过结构校验的字段;prev = 该榜已有行(可 null) */
function implausible(v, firstSeenTs, prev) {
  const now = Date.now();
  if (v.level > curveAt("level", v.playtime)) return "level";
  if (v.kills > curveAt("kills", v.playtime)) return "kills";
  if (v.max_zone > curveAt("zone", v.playtime)) return "zone";
  if (v.max_tower > v.kills) return "tower";   // 每层至少一杀(击杀计数单点 combat.ts)
  if (v.board === "power" && v.score > curveAt("power", v.playtime)) return "power";
  const ageSec = firstSeenTs != null ? (now - firstSeenTs) / 1000 : LB_BOUNDS.initialAgeSec;
  if (v.playtime > ageSec + LB_BOUNDS.offlineGraceSec) return "playtime";
  if (prev && prev.playtime != null) {
    const gapSec = Math.max(0, (now - (prev.updated_at ?? now)) / 1000);
    if (v.playtime > prev.playtime + gapSec + LB_BOUNDS.offlineGraceSec) return "playtime-delta";
  }
  return null;
}

/** uuid 首见时刻(不存在则记为现在);RETURNING 单语句读写 */
function firstSeenOf(uuid) {
  const r = db.prepare(
    "INSERT INTO first_seen (uuid, ts) VALUES (?, ?) " +
    "ON CONFLICT(uuid) DO UPDATE SET ts = ts RETURNING ts"
  ).get(uuid, Date.now());
  return r ? r.ts : Date.now();
}

// ---------------------------------------------------------------- 存档周期上云(/save-sync)
// 玩家端上行:POST {uuid,name,save}(无 token;独立小时限流 + 同套语义包络);
// 管理端:GET ?token=[&uuid=] 列表/单取,POST 带 X-Admin-Token 头 = 管理写回
// (跳过包络与限流,便于造测试档)。token 未配置时管理端点 503。
function syncRow(uuid) {
  return db.prepare(
    "SELECT playtime, updated_at FROM save_sync WHERE uuid = ?"
  ).get(uuid) || null;
}

function saveSyncPost(body, token) {
  const uuid = String(body.uuid ?? "");
  if (!UUID_RE.test(uuid)) return { body: { error: "bad uuid" }, status: 400 };
  const save = body.save;
  if (save === null || typeof save !== "object" || Array.isArray(save))
    return { body: { error: "bad save" }, status: 400 };
  const text = JSON.stringify(save);
  if (text.length > 60_000) return { body: { error: "save too large" }, status: 400 };

  const num = (v, dflt) => (typeof v === "number" && Number.isFinite(v))
    ? Math.max(0, Math.trunc(v)) : dflt;
  const v = {
    board: "sync", score: 0,
    kills: num(save.stats?.kills, 0), playtime: num(save.playtime, 0),
    level: Math.max(1, num(save.level, 1)), max_zone: Math.max(1, num(save.stats?.max_zone, 1)),
    max_tower: num(save.tower?.max_floor, 0),
  };
  const isAdmin = ADMIN_TOKEN !== "" && token !== "" && token === ADMIN_TOKEN;
  if (!isAdmin) {
    const bad = implausible(v, firstSeenOf(uuid), syncRow(uuid));
    if (bad) return { body: { error: `implausible ${bad}` }, status: 400 };
    if (!checkRate(uuid, "sync")) return { body: { error: "rate limited" }, status: 429 };
  }

  let name = cleanName(body.name);   // 空 = 保留库中旧名(INSERT 时给默认名)
  const now = Date.now();
  db.prepare(
    "INSERT INTO save_sync (uuid, name, save_json, playtime, level, kills, max_zone, max_tower, bytes, updated_at) " +
    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) " +
    "ON CONFLICT(uuid) DO UPDATE SET " +
    "name = CASE WHEN excluded.name = '' THEN save_sync.name ELSE excluded.name END, " +
    "save_json = excluded.save_json, playtime = excluded.playtime, level = excluded.level, " +
    "kills = excluded.kills, max_zone = excluded.max_zone, max_tower = excluded.max_tower, " +
    "bytes = excluded.bytes, updated_at = excluded.updated_at"
  ).run(uuid, name, text, v.playtime, v.level, v.kills, v.max_zone, v.max_tower, text.length, now);
  return { body: { ok: true, updated_at: now, bytes: text.length }, status: 200 };
}

function saveSyncGet(params, token) {
  if (ADMIN_TOKEN === "") return { body: { error: "admin token not configured" }, status: 503 };
  if (token !== ADMIN_TOKEN) return { body: { error: "bad token" }, status: 403 };
  const uuid = params.get("uuid") ?? "";
  if (uuid) {
    const r = db.prepare(
      "SELECT save_json, updated_at FROM save_sync WHERE uuid = ?"
    ).get(uuid);
    if (!r) return { body: { error: "not found" }, status: 404 };
    return { body: { uuid, save: JSON.parse(r.save_json), updated_at: r.updated_at }, status: 200 };
  }
  const rows = db.prepare(
    "SELECT uuid, name, level, playtime, kills, max_zone, max_tower, bytes, updated_at " +
    "FROM save_sync ORDER BY updated_at DESC LIMIT 200"
  ).all();
  return { body: { count: rows.length, saves: rows }, status: 200 };
}

// ---------------------------------------------------------------- 周榜(与 worker.js 同)
function weekKeyNow() {
  const t = new Date();
  const d = new Date(t.getFullYear(), t.getMonth(), t.getDate());
  d.setDate(d.getDate() + 4 - (d.getDay() || 7));
  const year = d.getFullYear();
  const jan1 = new Date(year, 0, 1);
  const week = Math.ceil(((d.getTime() - jan1.getTime()) / 86400000 + 1) / 7);
  return `${year}-W${week}`;
}

// ---------------------------------------------------------------- 读榜(与 worker.js 同)
function getBoard(params) {
  const board = params.get("b") ?? "";
  if (!BOARDS.includes(board)) return { body: { error: "bad board" }, status: 400 };
  const uuid = params.get("uuid") ?? "";
  const weekly = params.get("period") === "week";
  const week = weekly ? weekKeyNow() : null;
  const table = weekly ? "entries_weekly" : "entries";
  const top = weekly
    ? db.prepare(
        "SELECT uuid, name, score, kills, playtime, level, max_zone, updated_at " +
        `FROM ${table} WHERE board = ? AND week = ? ` +
        "ORDER BY score DESC, kills DESC, updated_at ASC LIMIT ?"
      ).all(board, week, TOP_N)
    : db.prepare(
        "SELECT uuid, name, score, kills, playtime, level, max_zone, updated_at " +
        `FROM ${table} WHERE board = ? ` +
        "ORDER BY score DESC, kills DESC, updated_at ASC LIMIT ?"
      ).all(board, TOP_N);
  if (weekly) db.prepare("DELETE FROM entries_weekly WHERE week < ?").run(week);
  const rows = top.map(r => {
    const { uuid: rowUuid, ...rest } = r;
    return { ...rest, is_me: rowUuid === uuid };   // 只回传 is_me,不外泄他人 uuid
  });
  let you = null;
  if (UUID_RE.test(uuid)) {
    const mine = fullRow(board, uuid, table, week);
    if (mine) {
      you = { rank: rankOf(board, mine.score, mine.kills, table, week),
              inTop: true, score: mine.score, kills: mine.kills };
    }
  }
  return { body: { board, period: weekly ? "week" : "all", top: rows, you }, status: 200 };
}

// ---------------------------------------------------------------- 提交(与 worker.js 同)
function submit(body) {
  const board = String(body.board ?? "");
  if (!BOARDS.includes(board)) return { body: { error: "bad board" }, status: 400 };
  const uuid = String(body.uuid ?? "");
  if (!UUID_RE.test(uuid)) return { body: { error: "bad uuid" }, status: 400 };

  const score = intOrNull(body.score, 1, board === "power" ? SCORE_MAX.power : SCORE_MAX.default);
  const kills = intOrNull(body.kills, 0, 1_000_000_000);
  const playtime = intOrNull(body.playtime, 0, 3.2e10);
  const level = intOrNull(body.level, 1, 5_000);
  const max_zone = intOrNull(body.max_zone, 1, 10_000);
  const max_tower = intOrNull(body.max_tower ?? 0, 0, 100_000);
  if ([score, kills, playtime, level, max_zone, max_tower].some(v => v === null))
    return { body: { error: "bad values" }, status: 400 };
  if ((board === "zone" && score !== max_zone) ||
      (board === "level" && score !== level) ||
      (board === "tower" && score !== max_tower))
    return { body: { error: "score mismatch" }, status: 400 };

  // 语义包络:拦"结构合法但物理不可能"的进度;先于限流(被拒不烧限流额度)
  const mine = fullRow(board, uuid);
  const bad = implausible(
    { board, score, kills, playtime, level, max_zone, max_tower },
    firstSeenOf(uuid), mine);
  if (bad) return { body: { error: `implausible ${bad}` }, status: 400 };

  if (!checkRate(uuid))
    return { body: { error: "rate limited" }, status: 429 };

  const name = cleanName(body.name) || `深渊行者#${uuid.slice(0, 4).toUpperCase()}`;
  const now = Date.now();

  if (mine && score < mine.score) {
    return { body: { rank: rankOf(board, mine.score, mine.kills),
                     inTop: true, updated: false }, status: 200 };
  }

  const cnt = db.prepare(
    "SELECT COUNT(*) AS n FROM entries WHERE board = ?").get(board);
  let qualified = (cnt?.n ?? 0) < TOP_N;
  if (!qualified) {
    const lowest = db.prepare(
      "SELECT score, kills FROM entries WHERE board = ? " +
      "ORDER BY score DESC, kills DESC, updated_at ASC LIMIT 1 OFFSET ?"
    ).get(board, TOP_N - 1);
    qualified = score > lowest.score ||
                (score === lowest.score && kills > lowest.kills);
  }

  if (qualified) {
    db.prepare(
      "INSERT INTO entries (board, uuid, name, score, kills, playtime, level, max_zone, max_tower, updated_at) " +
      "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) " +
      "ON CONFLICT(board, uuid) DO UPDATE SET " +
      "name = excluded.name, score = excluded.score, kills = excluded.kills, " +
      "playtime = excluded.playtime, level = excluded.level, " +
      "max_zone = excluded.max_zone, max_tower = excluded.max_tower, updated_at = excluded.updated_at"
    ).run(board, uuid, name, score, kills, playtime, level, max_zone, max_tower, now);
    db.prepare(
      "DELETE FROM entries WHERE board = ? AND rowid NOT IN (" +
      "  SELECT rowid FROM entries WHERE board = ? " +
      "  ORDER BY score DESC, kills DESC, updated_at ASC LIMIT ?)"
    ).run(board, board, TOP_N);
  }

  // —— 周榜(与 worker.js 同):独立于终身榜;同周只升不降,跨周覆盖 ——
  {
    const week = weekKeyNow();
    const wmine = fullRow(board, uuid, "entries_weekly", week);
    if (!(wmine && score < wmine.score)) {
      db.prepare(
        "INSERT INTO entries_weekly (board, uuid, week, name, score, kills, playtime, level, max_zone, max_tower, updated_at) " +
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) " +
        "ON CONFLICT(board, uuid) DO UPDATE SET " +
        "week = excluded.week, name = excluded.name, score = excluded.score, kills = excluded.kills, " +
        "playtime = excluded.playtime, level = excluded.level, " +
        "max_zone = excluded.max_zone, max_tower = excluded.max_tower, updated_at = excluded.updated_at"
      ).run(board, uuid, week, name, score, kills, playtime, level, max_zone, max_tower, now);
      db.prepare(
        "DELETE FROM entries_weekly WHERE board = ? AND week = ? AND rowid NOT IN (" +
        "  SELECT rowid FROM entries_weekly WHERE board = ? AND week = ? " +
        "  ORDER BY score DESC, kills DESC, updated_at ASC LIMIT ?)"
      ).run(board, week, board, week, TOP_N);
    }
  }

  const rank = rankOf(board, score, kills);
  return { body: { rank, inTop: qualified && rank <= TOP_N, updated: qualified }, status: 200 };
}

function fullRow(board, uuid, table = "entries", week = null) {
  const sql = week
    ? `SELECT score, kills, playtime, updated_at FROM ${table} WHERE board = ? AND uuid = ? AND week = ?`
    : `SELECT score, kills, playtime, updated_at FROM ${table} WHERE board = ? AND uuid = ?`;
  return (week
    ? db.prepare(sql).get(board, uuid, week)
    : db.prepare(sql).get(board, uuid)) || null;
}
function rankOf(board, score, kills, table = "entries", week = null) {
  const sql = week
    ? `SELECT COUNT(*) AS n FROM ${table} WHERE board = ? AND week = ? ` +
      "AND (score > ? OR (score = ? AND kills > ?))"
    : `SELECT COUNT(*) AS n FROM ${table} WHERE board = ? ` +
      "AND (score > ? OR (score = ? AND kills > ?))";
  const higher = week
    ? db.prepare(sql).get(board, week, score, score, kills)
    : db.prepare(sql).get(board, score, score, kills);
  return (higher?.n ?? 0) + 1;
}

// ---------------------------------------------------------------- HTTP
const server = http.createServer((req, res) => {
  const json = (out, status) => res.writeHead(status, { ...CORS, "Content-Type": "application/json; charset=utf-8" }).end(JSON.stringify(out));
  if (req.method === "OPTIONS") return res.writeHead(204, CORS).end();
  const url = new URL(req.url, `http://127.0.0.1:${PORT}`);
  try {
    if (url.pathname === "/healthz" && req.method === "GET")
      return json({ ok: true, boards: BOARDS.length, uptime: Math.round(process.uptime()) }, 200);
    if (url.pathname === "/board" && req.method === "GET") {
      const r = getBoard(url.searchParams);
      return json(r.body, r.status);
    }
    if (url.pathname === "/submit" && req.method === "POST") {
      let buf = "";
      req.on("data", c => { buf += c; if (buf.length > 64 * 1024) req.destroy(); });   // 64KB 上限
      req.on("end", () => {
        try { const r = submit(JSON.parse(buf || "{}")); json(r.body, r.status); }
        catch (e) { json({ error: String((e && e.message) || e) }, 400); }
      });
      return;
    }
    if (url.pathname === "/save-sync" && req.method === "GET") {
      const token = req.headers["x-admin-token"] ?? url.searchParams.get("token") ?? "";
      const r = saveSyncGet(url.searchParams, token);
      return json(r.body, r.status);
    }
    if (url.pathname === "/save-sync" && req.method === "POST") {
      const token = req.headers["x-admin-token"] ?? "";
      let buf = "";
      req.on("data", c => { buf += c; if (buf.length > 80 * 1024) req.destroy(); });   // 80KB 上限(整档)
      req.on("end", () => {
        try { const r = saveSyncPost(JSON.parse(buf || "{}"), token); json(r.body, r.status); }
        catch (e) { json({ error: String((e && e.message) || e) }, 400); }
      });
      return;
    }
    return json({ error: "not found" }, 404);
  } catch (e) {
    return json({ error: String((e && e.message) || e) }, 400);
  }
});
server.listen(PORT, () => console.log(`[leaderboard] listening on :${PORT} (db=${DB_PATH})`));
